import type { AppState } from "@/lib/types"

export const STORAGE_KEY = "wardline-demo-v2"

export function seedState(): AppState {
  return {
    patients: [
      {
        id: "pat-maya",
        firstName: "Maya",
        lastName: "Ellison",
        email: "maya.ellison@example.com",
        phone: "+15551201001",
        birthDate: "1978-04-12",
        gender: "Female",
        address: "18 Cedar Lane, Portland",
        emergencyContactName: "Noah Ellison",
        emergencyContactNumber: "+15551201002",
        primaryPhysician: "Amara Okonkwo",
        insuranceProvider: "Northwind Health",
        insurancePolicyNumber: "NW-441902",
        allergies: "Penicillin",
        currentMedication: "Lisinopril 10mg",
        pastMedicalHistory: "Osteoarthritis, right knee",
        treatmentConsent: true,
        privacyConsent: true,
      },
      {
        id: "pat-robert",
        firstName: "Robert",
        lastName: "Adeyemi",
        email: "robert.adeyemi@example.com",
        phone: "+15551201011",
        birthDate: "1965-11-02",
        gender: "Male",
        address: "904 Market Street, Portland",
        emergencyContactName: "Ada Adeyemi",
        emergencyContactNumber: "+15551201012",
        primaryPhysician: "Elias Chen",
        insuranceProvider: "Harbor Mutual",
        insurancePolicyNumber: "HM-22018",
        allergies: "None known",
        currentMedication: "",
        pastMedicalHistory: "Cholelithiasis",
        treatmentConsent: true,
        privacyConsent: true,
      },
      {
        id: "pat-linh",
        firstName: "Linh",
        lastName: "Tran",
        email: "linh.tran@example.com",
        phone: "+15551201021",
        birthDate: "1952-08-19",
        gender: "Female",
        address: "55 Willow Court, Beaverton",
        emergencyContactName: "Minh Tran",
        emergencyContactNumber: "+15551201022",
        primaryPhysician: "Priya Nair",
        insuranceProvider: "Northwind Health",
        insurancePolicyNumber: "NW-118334",
        allergies: "Latex",
        currentMedication: "Timolol drops",
        pastMedicalHistory: "Cataract, left eye",
        treatmentConsent: true,
        privacyConsent: true,
      },
      {
        id: "pat-helen",
        firstName: "Helen",
        lastName: "Brooks",
        email: "helen.brooks@example.com",
        phone: "+15551201031",
        birthDate: "1989-01-27",
        gender: "Female",
        address: "2 Oak Park, Portland",
        emergencyContactName: "Sam Brooks",
        emergencyContactNumber: "+15551201032",
        primaryPhysician: "Jonah Hale",
        insuranceProvider: "Cedar Plan",
        insurancePolicyNumber: "CP-90012",
        allergies: "",
        currentMedication: "",
        pastMedicalHistory: "",
        treatmentConsent: true,
        privacyConsent: true,
      },
      {
        id: "pat-omar",
        firstName: "Omar",
        lastName: "Farouk",
        email: "omar.farouk@example.com",
        phone: "+15551201041",
        birthDate: "1971-06-08",
        gender: "Male",
        address: "710 Division St, Portland",
        emergencyContactName: "Layla Farouk",
        emergencyContactNumber: "+15551201042",
        primaryPhysician: "Amara Okonkwo",
        insuranceProvider: "Harbor Mutual",
        insurancePolicyNumber: "HM-77410",
        allergies: "Iodine contrast",
        currentMedication: "Metformin",
        pastMedicalHistory: "Type 2 diabetes",
        treatmentConsent: true,
        privacyConsent: true,
      },
      {
        id: "pat-grace",
        firstName: "Grace",
        lastName: "Kim",
        email: "grace.kim@example.com",
        phone: "+15551201051",
        birthDate: "1996-12-03",
        gender: "Female",
        address: "41 Hawthorne, Portland",
        emergencyContactName: "June Kim",
        emergencyContactNumber: "+15551201052",
        primaryPhysician: "Priya Nair",
        insuranceProvider: "Cedar Plan",
        insurancePolicyNumber: "CP-33109",
        allergies: "",
        currentMedication: "",
        pastMedicalHistory: "",
        treatmentConsent: true,
        privacyConsent: true,
      },
    ],
    appointments: [
      {
        id: "apt-1",
        patientId: "pat-maya",
        physician: "Amara Okonkwo",
        schedule: "2026-10-02T09:30",
        reason: "Pre-op knee visit",
        note: "Review implant consent",
        status: "scheduled",
        cancellationReason: "",
      },
      {
        id: "apt-2",
        patientId: "pat-robert",
        physician: "Elias Chen",
        schedule: "2026-10-02T11:00",
        reason: "Post-op check",
        note: "",
        status: "scheduled",
        cancellationReason: "",
      },
      {
        id: "apt-3",
        patientId: "pat-helen",
        physician: "Jonah Hale",
        schedule: "2026-10-03T14:15",
        reason: "New patient intake",
        note: "",
        status: "pending",
        cancellationReason: "",
      },
      {
        id: "apt-4",
        patientId: "pat-omar",
        physician: "Amara Okonkwo",
        schedule: "2026-10-01T16:00",
        reason: "Diabetes follow-up",
        note: "Patient rescheduled",
        status: "cancelled",
        cancellationReason: "Travel conflict",
      },
      {
        id: "apt-5",
        patientId: "pat-grace",
        physician: "Priya Nair",
        schedule: "2026-10-06T08:45",
        reason: "Annual exam",
        note: "",
        status: "pending",
        cancellationReason: "",
      },
      {
        id: "apt-6",
        patientId: "pat-linh",
        physician: "Priya Nair",
        schedule: "2026-10-04T10:00",
        reason: "Eye pressure check",
        note: "",
        status: "scheduled",
        cancellationReason: "",
      },
    ],
    supplies: [
      {
        id: "sup-knee",
        name: "Total knee implant set",
        category: "Implant",
        sku: "IMP-KNEE-01",
        quantity: 6,
        unit: "set",
        reorderLevel: 2,
        unitCost: 4200,
        lastReconciledAt: "2026-09-28",
      },
      {
        id: "sup-cement",
        name: "Bone cement",
        category: "Consumable",
        sku: "CON-CEM-04",
        quantity: 14,
        unit: "pack",
        reorderLevel: 4,
        unitCost: 186,
        lastReconciledAt: "2026-09-01",
      },
      {
        id: "sup-drape",
        name: "Orthopedic drape pack",
        category: "Consumable",
        sku: "CON-DRP-12",
        quantity: 22,
        unit: "pack",
        reorderLevel: 8,
        unitCost: 34,
      },
      {
        id: "sup-clip",
        name: "Laparoscopic clip applier",
        category: "Consumable",
        sku: "CON-CLIP-2",
        quantity: 11,
        unit: "each",
        reorderLevel: 4,
        unitCost: 128,
      },
      {
        id: "sup-iol",
        name: "Intraocular lens",
        category: "Implant",
        sku: "IMP-IOL-21",
        quantity: 9,
        unit: "each",
        reorderLevel: 3,
        unitCost: 310,
      },
      {
        id: "sup-suture",
        name: "Vicryl suture 3-0",
        category: "Suture",
        sku: "SUT-VIC-30",
        quantity: 40,
        unit: "box",
        reorderLevel: 10,
        unitCost: 18,
      },
      {
        id: "sup-glove",
        name: "Sterile gloves, size 7",
        category: "PPE",
        sku: "PPE-GLV-7",
        quantity: 8,
        unit: "box",
        reorderLevel: 24,
        unitCost: 12,
        lotExpiry: "2026-10-20",
      },
      {
        id: "sup-prop",
        name: "Propofol 20ml",
        category: "Medication",
        sku: "MED-PRO-20",
        quantity: 2,
        unit: "vial",
        reorderLevel: 6,
        unitCost: 9.5,
        controlled: true,
        lotExpiry: "2026-10-12",
        lastReconciledAt: "2026-09-28",
      },
      {
        id: "sup-gauze",
        name: "Gauze sponges",
        category: "Consumable",
        sku: "CON-GAU-4",
        quantity: 30,
        unit: "pack",
        reorderLevel: 12,
        unitCost: 6.25,
        lotExpiry: "2026-09-01",
        lastReconciledAt: "2026-09-20",
      },
      {
        id: "sup-mesh",
        name: "Hernia mesh 15cm",
        category: "Implant",
        sku: "IMP-MSH-15",
        quantity: 4,
        unit: "each",
        reorderLevel: 2,
        unitCost: 640,
      },
    ],
    surgeries: [
      {
        id: "sx-knee",
        patientId: "pat-maya",
        procedure: "Total knee arthroplasty",
        leadSurgeon: "Amara Okonkwo",
        date: "2026-10-08",
        status: "planned",
        orRoom: "OR 2",
        materials: [
          {
            id: "mat-1",
            supplyId: "sup-knee",
            name: "Total knee implant set",
            quantity: 1,
            unitCost: 4200,
          },
          {
            id: "mat-2",
            supplyId: "sup-cement",
            name: "Bone cement",
            quantity: 2,
            unitCost: 186,
          },
          {
            id: "mat-3",
            supplyId: "sup-drape",
            name: "Orthopedic drape pack",
            quantity: 1,
            unitCost: 34,
          },
          {
            id: "mat-prop",
            supplyId: "sup-prop",
            name: "Propofol 20ml",
            quantity: 4,
            unitCost: 9.5,
          },
        ],
        labor: [
          {
            id: "lab-1",
            role: "Lead surgeon",
            staffName: "Amara Okonkwo",
            hours: 2.5,
            hourlyRate: 850,
          },
          {
            id: "lab-2",
            role: "Assistant surgeon",
            staffName: "Jonah Hale",
            hours: 2.5,
            hourlyRate: 420,
          },
          {
            id: "lab-3",
            role: "Anesthesiologist",
            staffName: "Elena Voss",
            hours: 3,
            hourlyRate: 480,
          },
          {
            id: "lab-4",
            role: "Scrub nurse",
            staffName: "Chris Patel",
            hours: 3.5,
            hourlyRate: 95,
          },
        ],
        charges: [
          { id: "chg-1", label: "Operating theatre time", amount: 2800 },
          { id: "chg-2", label: "Anesthesia gases and machine", amount: 640 },
          { id: "chg-3", label: "Recovery bay, 2 hours", amount: 420 },
        ],
      },
      {
        id: "sx-chole",
        patientId: "pat-robert",
        procedure: "Laparoscopic cholecystectomy",
        leadSurgeon: "Elias Chen",
        date: "2026-09-18",
        status: "completed",
        orRoom: "OR 1",
        materials: [
          {
            id: "mat-4",
            supplyId: "sup-clip",
            name: "Laparoscopic clip applier",
            quantity: 1,
            unitCost: 128,
          },
          {
            id: "mat-5",
            supplyId: "sup-suture",
            name: "Vicryl suture 3-0",
            quantity: 2,
            unitCost: 18,
          },
          {
            id: "mat-6",
            supplyId: "sup-gauze",
            name: "Gauze sponges",
            quantity: 3,
            unitCost: 6.25,
          },
        ],
        labor: [
          {
            id: "lab-5",
            role: "Lead surgeon",
            staffName: "Elias Chen",
            hours: 1.5,
            hourlyRate: 850,
          },
          {
            id: "lab-6",
            role: "Anesthesiologist",
            staffName: "Elena Voss",
            hours: 2,
            hourlyRate: 480,
          },
          {
            id: "lab-7",
            role: "Circulating nurse",
            staffName: "Riley Cho",
            hours: 2,
            hourlyRate: 85,
          },
        ],
        charges: [
          { id: "chg-4", label: "Operating theatre time", amount: 1600 },
          { id: "chg-5", label: "Laparoscopic tower", amount: 750 },
          { id: "chg-6", label: "Recovery bay, 1 hour", amount: 210 },
        ],
      },
      {
        id: "sx-cataract",
        patientId: "pat-linh",
        procedure: "Cataract extraction with IOL",
        leadSurgeon: "Priya Nair",
        date: "2026-10-14",
        status: "planned",
        orRoom: "OR 4",
        materials: [
          {
            id: "mat-7",
            supplyId: "sup-iol",
            name: "Intraocular lens",
            quantity: 1,
            unitCost: 310,
          },
          {
            id: "mat-8",
            supplyId: "sup-drape",
            name: "Orthopedic drape pack",
            quantity: 1,
            unitCost: 34,
          },
        ],
        labor: [
          {
            id: "lab-8",
            role: "Lead surgeon",
            staffName: "Priya Nair",
            hours: 0.75,
            hourlyRate: 850,
          },
          {
            id: "lab-9",
            role: "Scrub nurse",
            staffName: "Chris Patel",
            hours: 1.25,
            hourlyRate: 95,
          },
        ],
        charges: [
          { id: "chg-7", label: "Operating theatre time", amount: 900 },
          { id: "chg-8", label: "Phacoemulsification machine", amount: 480 },
        ],
      },
    ],
    reconciliations: [
      {
        id: "rec-seed",
        date: "2026-09-20",
        performedBy: "Amara Okonkwo",
        status: "signed",
        signedAt: "2026-09-20T16:10",
        signedBy: "Amara Okonkwo",
        entries: [
          {
            supplyId: "sup-gauze",
            expected: 32,
            counted: 30,
            reason: "wastage",
            resolved: true,
          },
        ],
      },
    ],
  }
}
