import type { DbSupply } from "@/lib/supabase"

/** Canonical demo stock — keep in sync with supabase/migrations seed + seed.ts supplies. */
export const SEED_SUPPLIES: DbSupply[] = [
  {
    id: "sup-knee",
    name: "Total knee implant set",
    category: "Implant",
    sku: "IMP-KNEE-01",
    quantity: 6,
    unit: "set",
    reorder_level: 2,
    unit_cost: 4200,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: "2026-09-28",
  },
  {
    id: "sup-cement",
    name: "Bone cement",
    category: "Consumable",
    sku: "CON-CEM-04",
    quantity: 14,
    unit: "pack",
    reorder_level: 4,
    unit_cost: 186,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: "2026-09-01",
  },
  {
    id: "sup-drape",
    name: "Orthopedic drape pack",
    category: "Consumable",
    sku: "CON-DRP-12",
    quantity: 22,
    unit: "pack",
    reorder_level: 8,
    unit_cost: 34,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: null,
  },
  {
    id: "sup-clip",
    name: "Laparoscopic clip applier",
    category: "Consumable",
    sku: "CON-CLIP-2",
    quantity: 11,
    unit: "each",
    reorder_level: 4,
    unit_cost: 128,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: null,
  },
  {
    id: "sup-iol",
    name: "Intraocular lens",
    category: "Implant",
    sku: "IMP-IOL-21",
    quantity: 9,
    unit: "each",
    reorder_level: 3,
    unit_cost: 310,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: null,
  },
  {
    id: "sup-suture",
    name: "Vicryl suture 3-0",
    category: "Suture",
    sku: "SUT-VIC-30",
    quantity: 40,
    unit: "box",
    reorder_level: 10,
    unit_cost: 18,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: null,
  },
  {
    id: "sup-glove",
    name: "Sterile gloves, size 7",
    category: "PPE",
    sku: "PPE-GLV-7",
    quantity: 8,
    unit: "box",
    reorder_level: 24,
    unit_cost: 12,
    controlled: false,
    lot_expiry: "2026-10-20",
    last_reconciled_at: null,
  },
  {
    id: "sup-prop",
    name: "Propofol 20ml",
    category: "Medication",
    sku: "MED-PRO-20",
    quantity: 2,
    unit: "vial",
    reorder_level: 6,
    unit_cost: 9.5,
    controlled: true,
    lot_expiry: "2026-10-12",
    last_reconciled_at: "2026-09-28",
  },
  {
    id: "sup-gauze",
    name: "Gauze sponges",
    category: "Consumable",
    sku: "CON-GAU-4",
    quantity: 30,
    unit: "pack",
    reorder_level: 12,
    unit_cost: 6.25,
    controlled: false,
    lot_expiry: "2026-09-01",
    last_reconciled_at: "2026-09-20",
  },
  {
    id: "sup-mesh",
    name: "Hernia mesh 15cm",
    category: "Implant",
    sku: "IMP-MSH-15",
    quantity: 4,
    unit: "each",
    reorder_level: 2,
    unit_cost: 640,
    controlled: false,
    lot_expiry: null,
    last_reconciled_at: null,
  },
]
